FROM golang:1.18.8-alpine

WORKDIR /app

RUN apk --no-cache add git && git clone https://github.com/Hera-system/webhook.git && cd webhook && go build .

WORKDIR /app/webhook

HEALTHCHECK --interval=30s --timeout=5s --start-period=5s CMD nc -z 127.0.0.1 7342

ENTRYPOINT ./webhook -conf=hera.config.json
