
version: '0.0.3'

services:
  site:
    image: oldtyt/hera:v0.0.3
    ports:
      - 9999:9999
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/hera
    restart: always

  db:
    image: postgres
    ports:
      - 5432
    environment:
      POSTGRES_DB: hera
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always
