version: '3.1'

services:
  site:
    image: oldtyt/hera:v0.0.8
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/hera
      - ALERTA_URL=http://alerta/auth/login
      - PORT=9997
    ports:
      - 9997:9997
    restart: always

  db:
    image: postgres
    ports:
      - 5432
    environment:
      POSTGRES_DB: hera
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always
