---
version: '3.8'

networks:
  net:
    external: true
    name: main_net

services:
  site:
    image: hera-system:local
    depends_on:
      - hera-db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@hera-db:5432/hera
      - ALERTA_URL=https://alerta.io/auth/login
      - CURRENT_ENV=development
      - PORT=9997
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=password
      - FLASK_DEBUG=1
      - DEBUG=True
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.services.hera-system.loadbalancer.server.port=9997
      - traefik.http.routers.hera-system.rule=Host(`hera-system.oldtyt.xyz`)
      - traefik.http.routers.hera-system.service=hera-system
      - traefik.http.routers.hera-system.entryPoints=http
    networks:
      - net

  hera-db:
    image: postgres
    environment:
      POSTGRES_DB: hera
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always
    networks:
      - net

  webhook-direct:
    depends_on:
      - site
    image: hera-webhook:local
    environment:
      TYPE: "direct"
    restart: always
    networks:
      - net

  webhook-reverse:
    depends_on:
      - site
    image: hera-webhook:local
    environment:
      TYPE: "reverse"
    restart: always
    networks:
      - net
