version: '3.1'

services:
  site:
    image: hera-system:local
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/hera
      - ALERTA_URL=https://alerta.io/auth/login
      - CURRENT_ENV=development
      - PORT=9997
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=password
      - FLASK_DEBUG=1
      - DEBUG=True
    ports:
      - 9997:9997
    restart: always

  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: hera
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always

  webhook:
    depends_on:
      - site
    image: hera-webhook:local
    restart: always
