name: Docker Image CI(DockerHUB)

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: oldtyt/hera
    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build the Docker image
      run: >-
        docker build
        -t $IMAGE_NAME
        -t $IMAGE_NAME:$(cat VERSION)
        -t $IMAGE_NAME:${{ steps.vars.outputs.SHORT_COMMIT_ID }}
        -t $IMAGE_NAME:${{github.ref_name}}
        -t $IMAGE_NAME:latest .
    - name: Added Docker tag
      run: docker tag hera/test:${{github.ref_name}} ${{secrets.DOCKER_USER}}/hera:${{github.ref_name}}

    - name: Docker Push
      run: docker push ${{secrets.DOCKER_USER}}/hera:${{github.ref_name}}
